openapi: 3.0.1
info:
  title: ' wiki/rest/api/content-states/'
  description: Needs description.
  termsOfService: https://atlassian.com/terms/
  version: 1.0.0
externalDocs:
  description: The online and complete version of the Confluence Cloud REST API docs.
  url: https://developer.atlassian.com/cloud/confluence/rest/
servers:
  - url: //your-domain.atlassian.net
tags: []
paths:
  /wiki/rest/api/content-states/delete:
    post:
      tags:
        - - - - Content states
      summary: Bulk remove content states from content
      description: >-
        Creates a long running task that Removes content state from draft or
        published versions of pages specified.


        **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**

        Content Edit Permission for a content to have its state removed via this
        endpoint.
      operationId: bulkRemoveContentStates
      parameters:
        - name: status
          in: query
          required: true
          description: Set status to one of [current,draft].
          schema:
            type: string
            enum:
              - current
              - draft
      requestBody:
        content:
          application/json:
            schema:
              required:
                - ids
              properties:
                ids:
                  type: array
                  items:
                    $ref: '#/components/schemas/ContentId'
      responses:
        '200':
          description: >-
            Returned if a task to remove content states is created. Returns the
            taskId.

            This task id can be passed into
            /wiki/rest/api/content-states/task/{taskId}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncId'
        '400':
          description: >-
            Returned if too many contents, no contents, no content state, or no
            status are passed in.
        '401':
          description: Returned if user not authenticated.
        '403':
          description: >-
            Returned if user not found or does not have permission for content
            stat
        '404':
          description: Returned if content cannot be found with the provided context.
      security:
        - oAuthDefinitions:
            - write:confluence-content
        - basicAuth: []
      x-atlassian-oauth2-scopes:
        - scheme: oAuthDefinitions
          state: Current
          scopes:
            - write:confluence-content
        - scheme: oAuthDefinitions
          state: Beta
          scopes:
            - write:content:confluence
            - read:content-details:confluence
      x-atlassian-data-security-policy:
        - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
  /wiki/rest/api/content-states/task/{taskId}:
    get:
      tags:
        - - - - Content states
      summary: Get update on long running task for setting of content state.
      description: >-
        Get Status of long running task that was previously created to set or
        remove content states from content.

        User must first create a task by passing in details to
        /wiki/rest/api/content-states PUT or DELETE endpoints.


        **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**

        Must have created long running task
      operationId: getTaskUpdate
      parameters:
        - name: taskId
          in: path
          schema:
            type: string
          description: >-
            taskId returned by put or delete requests to
            /wiki/rest/api/content-states
          required: true
      responses:
        '200':
          description: Task found. State of task is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentStateBulkSetTaskUpdate'
        '403':
          description: User not authenticated.
        '404':
          description: No long running task by calling user with given taskId found.
      security:
        - oAuthDefinitions:
            - read:confluence-content
        - basicAuth: []
      x-atlassian-oauth2-scopes:
        - scheme: oAuthDefinitions
          state: Current
          scopes:
            - read:confluence-content
        - scheme: oAuthDefinitions
          state: Beta
          scopes:
            - read:content:confluence
      x-atlassian-data-security-policy:
        - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
components:
  schemas:
    AsyncId:
      required:
        - asyncId
      type: object
      properties:
        asyncId:
          type: string
    ContentStateBulkSetTaskUpdate:
      required:
        - set
        - failed
        - success
        - percentage
      properties:
        set:
          type: array
          items:
            $ref: '#/components/schemas/ContentId'
        failed:
          type: array
          items:
            $ref: '#/components/schemas/ContentStateFailure'
        percentage:
          type: integer
          format: int64
        message:
          type: string
        state:
          $ref: '#/components/schemas/ContentState'
        success:
          type: boolean
      type: object
x-atlassian-narrative:
  documents:
    - title: About
      anchor: about
      body: >-
        This is the reference for the Confluence Cloud REST API. This API is the
        primary way to get and

        modify data in Confluence Cloud, whether you are developing an app or
        any other integration.

        Use it to interact with Confluence entities, like pages and blog posts,
        spaces, users, groups,

        and more.
    - title: Authentication and authorization
      anchor: auth
      body: >-
        **Authentication:** If you are building a Cloud app, authentication is
        implemented via JWT or OAuth 2.0, depending on what you are building
        (see [Security
        overview](https://developer.atlassian.com/cloud/confluence/security-overview/)).
        Otherwise, if you are authenticating directly against the REST API, the
        REST API supports basic auth (see [Basic auth for REST
        APIs](https://developer.atlassian.com/cloud/confluence/basic-auth-for-rest-apis/)).


        **Authorization:** If you are building a Cloud app, authorization can be
        implemented by
        [scopes](https://developer.atlassian.com/cloud/confluence/scopes/) or by
        [OAuth 2.0 user
        impersonation](https://developer.atlassian.com/cloud/confluence/oauth-2-jwt-bearer-tokens-for-apps).
        Otherwise, if you are making calls directly against the REST API,
        authorization is based on the user used in the authentication process.


        See [Security
        overview](https://developer.atlassian.com/cloud/confluence/security-overview/)
        for more details on authentication and authorization.
    - title: Status codes
      anchor: status-code
      body: >-
        The Confluence REST API uses the [standard HTTP status
        codes](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html).


        Responses that return an error status code will also return a response
        body, similar to the following:

        ```json

        {
          "statusCode": 404,
          "data": {
            "authorized": false,
            "valid": false,
            "errors": [
              {
                "message": {
                  "translation": "This is an example error message.",
                  "args": []
                }
              }
            ],
            "successful": false
          },
          "message": "This is an example error message."
        }

        ```
    - title: Using the REST API
      anchor: using
      body: >-
        **Expansion:** The Confluence REST API uses resource expansion: some
        parts of a resource are not returned unless explicitly specified. This
        simplifies responses and minimizes network traffic.


        To expand part of a resource in a request, use the `expand` query
        parameter and specify the entities to be expanded. If you need to expand
        nested entities, use the `.` dot notation. For example, the following
        request will expand information about the requested content's space and
        labels:

        ```

        GET /wiki/rest/api/content/{id}?expand=space,metadata.labels

        ```

        **Pagination:** The Confluence REST API uses pagination: a method that
        returns a response with multiple objects can only return a limited
        number at one time. This limits the size of responses and conserves
        server resources.


        Use the 'limit' and 'start' query parameters to specify pagination:


        - `limit` is the number of objects to return per page. This may be
        restricted by system limits.

        - `start` is the index of the first item returned in the page of
        results. The base index is 0.


        For example, the following request will return ten content objects,
        starting from the fifth object.

        ```

        GET /wiki/rest/api/content?start=4&limit=10

        ```

        **Special headers:**


        - `X-Atlassian-Token: no-check` request header must be specified for
        methods

        that are protected from Cross Site Request Forgery (XSRF/CSRF) attacks.
        This is

        stated in the method description, if required. For more information, see
        this

        [KB
        article](https://confluence.atlassian.com/cloudkb/xsrf-check-failed-when-calling-cloud-apis-826874382.html).
    - title: Capabilities
      anchor: capabilities
      body: >-
        **Webhooks:** A webhook is a user-defined callback over HTTP. You can
        use Confluence webhooks to notify your app or web application when
        certain events occur in Confluence. For example, when a page is created
        or updated. To learn more, see
        [Webhooks](https://developer.atlassian.com/cloud/confluence/modules/webhook/).


        **Content properties:** Content properties are a key-value storage
        associated with a piece of Confluence content. If you are building an
        app, this is one form of persistence that you can use. You can use the
        Confluence REST API to get, update, and delete content properties. To
        learn more, see [Content properties in the REST
        API](https://developer.atlassian.com/cloud/confluence/content-properties/).


        **CQL:** The Confluence Query Language (CQL) allows you to perform
        complex searches for content using an SQL-like syntax in the `search`
        resource. To learn more, see [Advanced searching using
        CQL](https://developer.atlassian.com/cloud/confluence/advanced-searching-using-cql/).
